name = "filoject"
description = "Dependency injection framework for Ada"
version = "0.2.0-dev"

authors = ["René Hartmann"]
maintainers = ["René Hartmann <rhartmann@users.sourceforge.net>"]
maintainers-logins = ["rehartmann"]
licenses = "BSD-3-Clause"
website = ""
tags = ["di"]
